### ISSUE TITLE
can not set pub and priv key on peer-info

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-peer-book#33]
They don't have setters currently so 

- https://github.com/libp2p/js-peer-book/blob/master/src/index.js#L66
- https://github.com/libp2p/js-peer-book/blob/master/src/index.js#L70

throw. Should add a test here for this and add setters on peer-info

**Comment by dignifiedquire** [comment]
cc @diasdavid

**Comment by daviddias** [comment]
You mean peer-id, right? https://github.com/libp2p/js-peer-id/blob/master/src/index.js#L34-L46

Got it

**Comment by daviddias** [comment]
This has been done :)
