### ISSUE TITLE
Add ability to record latency information

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-peer-book#34]

**Comment by jayarjo** [comment]
Why do you folks keep issues for merged fixes open?

**Comment by JustMaier** [comment]
Doesn't look like this has been implemented yet, which appears to mean that the js peer-book isn't at parity with the go peer-book.

**Comment by tapaswenipathak** [comment]
Hi folks: Can I take the ticket?

**Comment by JustMaier** [comment]
@tapaswenipathak that'd be awesome!

**Comment by jacobheun** [comment]
Issue moved to [libp2p/js-libp2p #556](https://github.com/libp2p/js-libp2p/issues/556) via [**ZenHub**](https://www.zenhub.com/)
